require "config.plugins_config.whichkey"
require "config.plugins_config.colorscheme"
require "config.plugins_config.project"
require "config.plugins_config.trouble" -- Amazing
require "config.plugins_config.telescope" -- Amazing
require "config.plugins_config.treesitter" -- Amazing
-- require "config.plugins_config.nvimtree"
require "config.plugins_config.utils"
require "config.plugins_config.gitsigns" -- Nice
require "config.plugins_config.comment"
require "config.plugins_config.autopairs"
require "config.plugins_config.lualine"
require "config.plugins_config.bufferline"
require "config.plugins_config.symbols_outline"
-- require "config.plugins_config.startify"
require "config.plugins_config.toggleterm"
require "config.plugins_config.lspsaga"
require "config.plugins_config.cmp"
require "config.plugins_config.lsp"
require "config.plugins_config.orgmode"
-- require "config.plugins_config.neorg"
require "config.plugins_config.dashboard"
require "config.plugins_config.conda"
require "config.plugins_config.ranger"
require "config.plugins_config.colorizer"
require "config.plugins_config.sneak"
require "config.plugins_config.neogit"
require "config.plugins_config.vimtex"
require "config.plugins_config.scrollbar"
-- require "config.plugins_config.octo"
-- require "config.plugins_config.litee"
