rm -rf ~/dotfiles/emacs/.config/emacs/auto-save-list
rm -rf ~/dotfiles/emacs/.config/emacs/straight
rm -rf ~/dotfiles/emacs/.config/emacs/eln-cache
rm -rf ~/dotfiles/emacs/.config/emacs/elpa
rm -rf ~/dotfiles/emacs/.config/emacs/games
rm -rf ~/dotfiles/emacs/.config/emacs/*#
rm -rf ~/dotfiles/emacs/.config/emacs/#*
rm -rf ~/dotfiles/emacs/.config/emacs/.#*
rm -rf ~/dotfiles/emacs/.config/emacs/config/*#
rm -rf ~/dotfiles/emacs/.config/emacs/config/#*
rm -rf ~/dotfiles/emacs/.config/emacs/config/.#*
rm -rf ~/dotfiles/emacs/.config/emacs/projects
rm -rf ~/dotfiles/emacs/.config/emacs/recentf
rm -rf ~/dotfiles/emacs/.config/emacs/tramp
rm -rf ~/dotfiles/emacs/.config/emacs/transient
rm -rf ~/dotfiles/emacs/.config/emacs/*.elc
rm -rf ~/dotfiles/emacs/.config/emacs/config/*.elc
