rm -rf ~/dotfiles/emacs/.config/emacs/auto-save-list
rm -rf ~/dotfiles/emacs/.config/emacs/straight
rm -rf ~/dotfiles/emacs/.config/emacs/eln-cache
rm -rf ~/dotfiles/emacs/.config/emacs/elpa
rm -rf ~/dotfiles/emacs/.config/emacs/games
rm -rf ~/dotfiles/emacs/.config/emacs/*#
rm -rf ~/dotfiles/emacs/.config/emacs/#*
rm -rf ~/dotfiles/emacs/.config/emacs/.#*
rm -rf ~/dotfiles/emacs/.config/emacs/config/*#
rm -rf ~/dotfiles/emacs/.config/emacs/config/#*
rm -rf ~/dotfiles/emacs/.config/emacs/config/.#*
