[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B]"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u001B\\"
key = "Backslash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B:"
key = "Semicolon"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B>"
key = "Period"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B<"
key = "Comma"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B\""
key = "\""
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B\r"
key = "Return"
mods = "Command"

[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[colors.normal]
black = "#1e2127"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.primary]
background = "#1e2127"
foreground = "#abb2bf"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[keyboard]

# alt_send_esc = true # not used anymore

